name: ci

on:
  push:
    branches:
      - main
      - 'dev'
  pull_request:
    branches:
      - main
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {{cookiecutter.python_major_version}}.{{cookiecutter.python_minor_version}}
      uses: actions/setup-python@v3
      with:
        python-version: {{cookiecutter.python_major_version}}.{{cookiecutter.python_minor_version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pip-tools
        pip-compile --output-file requirements.txt requirements.in requirements_dev.in
        python -m  pip install coverage
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run tests with pytest
      run: |
        coverage run -m pytest